### ISSUE TITLE
Not compatible with Android Maps SDK 3.0 beta

### ISSUE THREAD

**Issue by ryust** [sarweshkumar47/Curve-Fit#2]
As the title says, this library is not compatible with the new Android Maps SDK coming out. Any idea if/when a compatible version is coming out?

I really like this library, but will have to pull it from my app if this can't be resolved soon.

**Comment by sarweshkumar47** [comment]
> As the title says, this library is not compatible with the new Android Maps SDK coming out. Any idea if/when a compatible version is coming out?
> 
> I really like this library, but will have to pull it from my app if this can't be resolved soon.

Working on it. The new version will be released shortly.

**Comment by sarweshkumar47** [comment]
New [2.0.0 beta version](https://github.com/sarweshkumar47/Curve-Fit/tree/curve-fit-2.0.0-beta) is released. Please check.
