### ISSUE TITLE
Adjust curvature

### ISSUE THREAD

**Issue by ryust** [sarweshkumar47/Curve-Fit#3]
Is there any way to adjust the curvature of the lines? Actually, I'd like to be able to create a straight line for some datasets.

**Comment by sarweshkumar47** [comment]
> Is there any way to adjust the curvature of the lines? Actually, I'd like to be able to create a straight line for some datasets.

Use `setAlpha` option. Setting the alpha value to `0` gives you a straight line in most cases. If you want a perfectly straight line, use `setComputePointsBasedOnScreenPixels` option and set it to `true` (Read the limitation of this method before using it).

If you want to vary the shape and direction of a curve, try changing the alpha value (Default value is 0.5 and it can vary from -1 to +1). To test the functionality, check the demo application available on [Playstore](https://play.google.com/store/apps/details?id=com.makesense.labs.curvefitexample).

<img src="https://lh3.googleusercontent.com/9ASY5WmPCjTqoUWYzQ94PdBJswJaskyY_W-S7zTPkIpe43bxdzmuEGqWN7qEzg_Ziqc=w1440-h620" alt="sample_india" width="220"/>

**Comment by ryust** [comment]
Ahhh, I was thinking alpha was for transparency. This will work. Thanks for the quick reply and really nice library.

**Comment by sarweshkumar47** [comment]
I'm happy to hear that. Please let me know if you think any new feature can be added to this library or if it requires any improvement. By the way, thanks for informing me about compatibleness of this library with Maps 3.0 beta.
