### ISSUE TITLE
CurveOptions width format?

### ISSUE THREAD

**Issue by ryust** [sarweshkumar47/Curve-Fit#5]
Is CurveOptions width in pixels or dips?

**Comment by sarweshkumar47** [comment]
Using `width` option, sets the width of a curve in screen pixels. You can set different options in `CurveOptions` object similar to `PolyLineOptions`. The default value is 10.

**Comment by ryust** [comment]
Just to be sure I understand the response... the format is CurveOptions.width(x) where x is pixels, not dip? Correct?

**Comment by sarweshkumar47** [comment]
Yes
