### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by ryust** [sarweshkumar47/Curve-Fit#7]
How is this integrated into a project? Via a gradle library dependency (like the old one) or put in the libs directory as an APK? I can't get it to work.

**Comment by sarweshkumar47** [comment]
Are you asking about integrating this library to an existing Android project? If not, can you give me a little more details to understand your question better?

**Comment by ryust** [comment]
Yes, an existing project. What is the gradle dependency syntax? Is the library on maven?

**Comment by sarweshkumar47** [comment]
It is available in jcenter, maven and jitpack too. Please check the readme file for adding this library to the project.

**Comment by ryust** [comment]
I see no readme file for the 2.0 beta. I already have the 1.1.1 version installed in my project, but am planning to use the new Android maps 3.0 SDK with the new curve-fit.

**Comment by sarweshkumar47** [comment]
I'm not seeing any problem in viewing the readme file. Just click on this [link](https://github.com/sarweshkumar47/Curve-Fit/blob/curve-fit-2.0.0-beta/README.md).

**Comment by ryust** [comment]
There it is...

The problem is if you start [here](https://github.com/sarweshkumar47/Curve-Fit) then click the [CurveFit-2.0.0-beta](https://github.com/sarweshkumar47/Curve-Fit/releases/tag/version_2_0_0_beta) link it doesn't go to the link you just provided. I see now you can use the GIT beta branch to reach it also. It would be much less confusing if on the beta link you go directly to the page instead.

**Comment by sarweshkumar47** [comment]
Suggestion accepted :)
