### ISSUE TITLE
show just once

### ISSUE THREAD

**Issue by meysam2594** [sarweshkumar47/Curve-Fit#8]
hi there !
thanks for useful library , i have one problem and one question
1 - in my case i have few item when click on item show you dialog  with map fragment and show the curved polyline but thats work for first time and the next time the polyline dosn't show .
2  - can i set animation to polyline color change ?!

**Comment by sarweshkumar47** [comment]
Question 1: This might be helpful: https://github.com/sarweshkumar47/Curve-Fit/issues/4#issuecomment-518660918

Question 2: I haven't tried applying an animation to the curve (polyline). I think it's doable.

**Comment by meysam2594** [comment]
thank you for solution it's work
